-- 가입 신청자는 JOINED_AT이 없고, 승인된 회원에게만 실제 가입 시각을 기록한다.
-- 애플리케이션의 JOINED_AT 명시 INSERT를 사용하기 전에 이 스크립트를 적용한다.
-- 기존 PENDING/REJECTED 행의 JOINED_AT 값은 삭제되므로 적용 전에 확인한다.

ALTER TABLE CAFE_MEMBER MODIFY (JOINED_AT NULL);

ALTER TABLE CAFE_MEMBER MODIFY (JOINED_AT DEFAULT NULL);

UPDATE CAFE_MEMBER
SET JOINED_AT = NULL
WHERE STATUS IN ('PENDING', 'REJECTED')
  AND JOINED_AT IS NOT NULL;

COMMIT;
